sudo: false

language: node_js

node_js:
  - 6
  - 4

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run browserify
  - npm run build-fixture
  - npm run bundle-demo
  - npm run rework
  - npm run test
